services:
  - type: web
    name: teens-camp
    runtime: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: APP_NAME
        value: "Teen Camp"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: https://teens-camp-2lyz.onrender.com
      - key: DB_CONNECTION
        value: sqlite
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: error
      - key: APP_KEY
        sync: false
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: smtp-relay.brevo.com
      - key: MAIL_PORT
        value: "587"
      - key: MAIL_ENCRYPTION
        value: tls
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_FROM_ADDRESS
        value: karis123wer@gmail.com
      - key: MAIL_FROM_NAME
        value: "Teen Camp Kenya"
      - key: BREVO_API_KEY
        sync: false
      - key: BREVO_SMTP_KEY
        sync: false
