@extends('layouts.backoffice')

@section('title', 'Campaign Fundraising POS & Catalogue')

@section('content')
<div class="container-fluid">
    <div class="d-flex align-items-center justify-content-between mb-4">
        <div>
            <h3 class="fw-bold mb-0">Campaign Fundraising Operations</h3>
            <p class="text-muted small mb-0">
                Record product sales, track weekly holding profits, and transfer approved proceeds into the Adopt-a-Teen Kitty.
            </p>
        </div>
        <div class="d-flex gap-2">
            @if($isHead)
                <button type="button" class="btn btn-camp-outline-red btn-sm" data-bs-toggle="modal" data-bs-target="#addProductModal">
                    <i class="bi bi-tag-fill me-1"></i> Add Catalogue Product
                </button>
            @endif
            <button type="button" class="btn btn-camp-red btn-sm" data-bs-toggle="modal" data-bs-target="#recordSaleModal">
                <i class="bi bi-cart-plus-fill me-1"></i> Record New Sale
            </button>
        </div>
    </div>

    <!-- Profit Summary Cards -->
    <div class="row g-3 mb-4">
        <div class="col-sm-6 col-md-4">
            <div class="camp-card p-3">
                <span class="text-muted small text-uppercase fw-bold">My Personal Recorded Profit</span>
                <div class="fs-3 fw-bold text-success mt-1">KES {{ number_format($myProfit, 2) }}</div>
                <div class="small text-muted">Generated by your sales</div>
            </div>
        </div>

        <div class="col-sm-6 col-md-4">
            <div class="camp-card p-3">
                <span class="text-muted small text-uppercase fw-bold">Active Week Holding Profit</span>
                <div class="fs-3 fw-bold text-danger mt-1">
                    KES {{ number_format($activeBatch ? $activeBatch->total_profit_amount : 0, 2) }}
                </div>
                <div class="small text-muted">
                    Holding batch: <strong>{{ $activeBatch ? $activeBatch->week_label : 'Pending' }}</strong> (Not in kitty yet)
                </div>
            </div>
        </div>

        <div class="col-sm-6 col-md-4">
            <div class="camp-card p-3 border-danger">
                <span class="text-muted small text-uppercase fw-bold">Season Cumulative Profit</span>
                <div class="fs-3 fw-bold mt-1">KES {{ number_format($totalProfit, 2) }}</div>
                <div class="small text-muted">All campaign products sold</div>
            </div>
        </div>
    </div>

    <div class="row g-4 mb-4">
        <!-- Product Catalogue (Visible to all, editable by Head/Admin) -->
        <div class="col-lg-5">
            <div class="camp-card p-4 h-100">
                <div class="d-flex justify-content-between align-items-center mb-3 border-bottom pb-2">
                    <h5 class="fw-bold mb-0"><i class="bi bi-tag text-danger me-2"></i> Catalogue</h5>
                    @if($isHead)
                        <button type="button" class="btn btn-camp-red btn-sm" data-bs-toggle="modal" data-bs-target="#addProductModal">
                            <i class="bi bi-plus-circle me-1"></i> Add Product
                        </button>
                    @endif
                </div>

                <div class="table-responsive">
                    <table class="table table-camp align-middle">
                        <thead>
                            <tr>
                                <th>Product</th>
                                <th>Selling</th>
                                <th>Profit</th>
                                <th class="text-end">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse($products as $p)
                                <tr>
                                    <td>
                                        <div class="fw-bold">{{ $p->name }}</div>
                                        <div class="small text-muted">Cost: KES {{ number_format($p->unit_cost, 2) }}</div>
                                    </td>
                                    <td class="fw-bold">KES {{ number_format($p->unit_price, 2) }}</td>
                                    <td><span class="badge bg-success-subtle text-success fw-bold">+KES {{ number_format($p->profit_per_unit, 2) }}</span></td>
                                    <td class="text-end">
                                        <div class="d-flex align-items-center justify-content-end gap-1">
                                            <button type="button" class="btn btn-outline-danger btn-sm py-1 px-2" onclick="quickSale({{ $p->id }}, '{{ addslashes($p->name) }}', {{ $p->unit_price }})" title="Record quick sale">
                                                <i class="bi bi-plus-lg"></i> Sale
                                            </button>
                                            @if($isHead)
                                                <button type="button" class="btn btn-outline-secondary btn-sm py-1 px-2 text-danger" data-bs-toggle="modal" data-bs-target="#deleteProductModal{{ $p->id }}" title="Remove item from catalogue (PIN required)">
                                                    <i class="bi bi-trash3-fill"></i>
                                                </button>
                                            @endif
                                        </div>
                                    </td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="4" class="text-center text-muted py-3">No products in catalogue yet.</td>
                                </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

        <!-- Recent Sales Log -->
        <div class="col-lg-7">
            <div class="camp-card p-4 h-100">
                <div class="d-flex justify-content-between align-items-center mb-3 border-bottom pb-2">
                    <h5 class="fw-bold mb-0"><i class="bi bi-clock-history text-danger me-2"></i> Recent Transaction Log</h5>
                    <button type="button" class="btn btn-camp-red btn-sm" data-bs-toggle="modal" data-bs-target="#recordSaleModal">
                        <i class="bi bi-plus-circle me-1"></i> Record Sale
                    </button>
                </div>

                <div class="table-responsive">
                    <table class="table table-camp align-middle">
                        <thead>
                            <tr>
                                <th>Product & Qty</th>
                                <th>Seller</th>
                                <th>Total Sale</th>
                                <th>Profit</th>
                                <th>Time</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse($recentSales as $sale)
                                <tr>
                                    <td>
                                        <div class="fw-bold">{{ $sale->product->name }}</div>
                                        <div class="small text-muted">{{ $sale->quantity }} units @ KES {{ number_format($sale->unit_price, 2) }}</div>
                                    </td>
                                    <td>
                                        <span class="small">{{ $sale->seller->name }}</span>
                                    </td>
                                    <td class="fw-bold">KES {{ number_format($sale->total_amount, 2) }}</td>
                                    <td class="fw-bold text-success">+KES {{ number_format($sale->total_profit, 2) }}</td>
                                    <td class="small text-muted">{{ $sale->sold_at->format('M d, H:i') }}</td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="5" class="text-center text-muted py-4">No sales recorded yet.</td>
                                </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <!-- Weekly Holding Batches & Kitty Integration -->
    <div class="camp-card p-4">
        <div class="d-flex justify-content-between align-items-center mb-3 border-bottom pb-2">
            <div>
                <h5 class="fw-bold mb-0"><i class="bi bi-calendar-check text-danger me-2"></i> Weekly Holding Batches & Kitty Integration</h5>
                <p class="text-muted small mb-0">Sales accumulate in weekly holding batches. Once approved by Admin or Campaign Head, profits move directly into the Adopt-a-Teen Kitty ledger.</p>
            </div>
        </div>

        <div class="table-responsive">
            <table class="table table-camp align-middle">
                <thead>
                    <tr>
                        <th>Batch Label</th>
                        <th>Dates</th>
                        <th>Total Sales</th>
                        <th>Holding Profit</th>
                        <th>Status</th>
                        <th>Reviewed By</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse($batches as $b)
                        <tr>
                            <td class="fw-bold">{{ $b->week_label }}</td>
                            <td>{{ $b->week_start->format('M d') }} - {{ $b->week_end->format('M d, Y') }}</td>
                            <td>KES {{ number_format($b->total_sales_amount, 2) }}</td>
                            <td class="fw-bold text-success fs-6">KES {{ number_format($b->total_profit_amount, 2) }}</td>
                            <td>
                                @if($b->status === 'approved')
                                    <span class="badge bg-success"><i class="bi bi-check-circle-fill me-1"></i> Approved & in Kitty</span>
                                @elseif($b->status === 'returned')
                                    <span class="badge bg-danger"><i class="bi bi-arrow-return-left me-1"></i> Returned for Correction</span>
                                @else
                                    <span class="badge bg-warning text-dark"><i class="bi bi-clock me-1"></i> Pending Admin Approval</span>
                                @endif
                            </td>
                            <td class="small text-muted">{{ $b->approver ? $b->approver->name : 'Pending' }}</td>
                            <td>
                                @if($b->status === 'pending_review' && ($isHead))
                                    <form action="{{ route('backoffice.campaign.batches.approve', $b) }}" method="POST" class="d-inline">
                                        @csrf
                                        <button type="submit" class="btn btn-success btn-sm" onclick="return confirm('Approve batch and transfer KES {{ number_format($b->total_profit_amount, 2) }} into the Adopt-a-Teen Kitty ledger?')">
                                            <i class="bi bi-check-lg me-1"></i> Approve to Kitty
                                        </button>
                                    </form>
                                @endif
                            </td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="7" class="text-center text-muted py-3">No batches created yet.</td>
                        </tr>
                    @endforelse
                </tbody>
            </table>
        </div>
    </div>

    <!-- Record Sale Modal -->
    <div class="modal fade" id="recordSaleModal" tabindex="-1">
        <div class="modal-dialog">
            <div class="modal-content">
                <form action="{{ route('backoffice.campaign.sale.record') }}" method="POST">
                    @csrf
                    @if($activeBatch)
                        <input type="hidden" name="batch_id" value="{{ $activeBatch->id }}">
                    @endif
                    <div class="modal-header">
                        <h5 class="modal-title fw-bold">Record Campaign Sale</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                    </div>
                    <div class="modal-body">
                        <div class="mb-3">
                            <label class="form-label fw-semibold">Select Product</label>
                            <select class="form-select" name="product_id" id="modal_product_id" required>
                                <option value="">-- Choose Catalogue Item --</option>
                                @foreach($products as $p)
                                    <option value="{{ $p->id }}" data-price="{{ $p->unit_price }}" data-profit="{{ $p->profit_per_unit }}">
                                        {{ $p->name }} (KES {{ number_format($p->unit_price, 2) }} - Profit: KES {{ number_format($p->profit_per_unit, 2) }})
                                    </option>
                                @endforeach
                            </select>
                        </div>
                        <div class="mb-3">
                            <label class="form-label fw-semibold">Quantity Sold</label>
                            <input type="number" class="form-control" name="quantity" id="modal_quantity" value="1" min="1" required>
                        </div>
                        <div class="alert alert-dark small mb-0">
                            Recording against Batch: <strong>{{ $activeBatch ? $activeBatch->week_label : 'Current Week' }}</strong>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary btn-sm" data-bs-dismiss="modal">Cancel</button>
                        <button type="submit" class="btn btn-camp-red btn-sm">Record Transaction</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <!-- Add Product Modal (Head / Admin) -->
    @if($isHead)
        <div class="modal fade" id="addProductModal" tabindex="-1">
            <div class="modal-dialog">
                <div class="modal-content">
                    <form action="{{ route('backoffice.campaign.products.add') }}" method="POST">
                        @csrf
                        <div class="modal-header">
                            <h5 class="modal-title fw-bold">Add Catalogue Product</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                        </div>
                        <div class="modal-body">
                            <div class="mb-3">
                                <label class="form-label fw-semibold">Product Name</label>
                                <input type="text" class="form-control" name="name" placeholder="e.g. Camp Water Bottle, Christian T-Shirt" required>
                            </div>
                            <div class="row g-2">
                                <div class="col-6">
                                    <label class="form-label fw-semibold">Unit Cost Price (KES)</label>
                                    <input type="number" step="1" class="form-control" name="unit_cost" placeholder="250" required>
                                </div>
                                <div class="col-6">
                                    <label class="form-label fw-semibold">Selling Price (KES)</label>
                                    <input type="number" step="1" class="form-control" name="unit_price" placeholder="500" required>
                                </div>
                            </div>
                            <div class="form-text small mt-2">
                                System will calculate profit per unit automatically (Selling Price - Cost).
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary btn-sm" data-bs-dismiss="modal">Cancel</button>
                            <button type="submit" class="btn btn-camp-red btn-sm">Save to Catalogue</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        {{-- Delete Product Modals with Account PIN Confirmation --}}
        @foreach($products as $p)
            <div class="modal fade" id="deleteProductModal{{ $p->id }}" tabindex="-1" aria-labelledby="deleteProductLabel{{ $p->id }}" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content border-0 text-white shadow-lg" style="background:#18181c; border-radius:14px; border: 1px solid rgba(255,255,255,0.08);">
                        <form action="{{ route('backoffice.campaign.products.delete', $p) }}" method="POST">
                            @csrf
                            @method('DELETE')
                            <div class="modal-header border-bottom border-secondary border-opacity-25 px-4 py-3" style="background:#141418;">
                                <h6 class="modal-title fw-bold text-danger mb-0 d-flex align-items-center gap-2" id="deleteProductLabel{{ $p->id }}">
                                    <i class="bi bi-exclamation-triangle-fill"></i> Remove Item from Catalogue
                                </h6>
                                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal"></button>
                            </div>
                            <div class="modal-body px-4 py-3">
                                <div class="p-3 rounded bg-dark border border-secondary border-opacity-50 mb-3">
                                    <div class="fs-5 fw-bold text-white mb-1">{{ $p->name }}</div>
                                    <div class="text-muted small">
                                        Cost: <strong class="text-light">KES {{ number_format($p->unit_cost, 2) }}</strong> ·
                                        Price: <strong class="text-danger">KES {{ number_format($p->unit_price, 2) }}</strong> ·
                                        Profit: <strong class="text-success">+KES {{ number_format($p->profit_per_unit, 2) }}</strong>
                                    </div>
                                </div>
                                <p class="small text-muted mb-3">
                                    Are you sure you want to remove <strong>{{ $p->name }}</strong> from the active product catalogue? To authorize removal, enter your <strong>4-digit account PIN</strong>:
                                </p>
                                <div class="mb-2">
                                    <label class="form-label small fw-semibold text-light mb-1">
                                        Account PIN Confirmation <span class="text-danger">*</span>
                                    </label>
                                    <input type="password" name="pin" maxlength="4" pattern="[0-9]{4}" inputmode="numeric" class="form-control form-control-lg bg-dark text-white border-secondary text-center font-monospace fs-3 fw-bold" placeholder="••••" required autocomplete="off" style="letter-spacing: 8px;">
                                    <div class="form-text text-muted small">Enter your staff account PIN to authorize this deletion.</div>
                                </div>
                            </div>
                            <div class="modal-footer border-top border-secondary border-opacity-25 px-4 py-3" style="background:#141418;">
                                <button type="button" class="btn btn-secondary btn-sm" data-bs-dismiss="modal">Cancel</button>
                                <button type="submit" class="btn btn-danger btn-sm px-4 fw-bold">
                                    <i class="bi bi-trash3-fill me-1"></i> Confirm &amp; Remove Item
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        @endforeach
    @endif
</div>

@push('scripts')
<script>
    function quickSale(productId, productName, price) {
        const select = document.getElementById('modal_product_id');
        if (select) {
            select.value = productId;
            const modal = new bootstrap.Modal(document.getElementById('recordSaleModal'));
            modal.show();
        }
    }
</script>
@endpush
@endsection
